extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: $HOST_IP:4317
      http: 
        endpoint: $HOST_IP:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "node-exporter"
          scrape_interval: 10s
          static_configs:
            - targets: ["node-exporter:9100"]
processors:
  batch:

exporters:
   prometheus:
     endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [otlp,prometheus]
      processors: [batch]
      exporters: [prometheus]

  extensions: [health_check, pprof, zpages]
